## Estudio de Convergencia: Calculos con PyGBe

### Lisozima 1hel sometida a un Campo Electrico Externo

#### Parametros PyGBe

	Use GPU                 : 0
	P                       : 6
	threshold               : 0.50
	theta                   : 0.50
	NCRIT                   : 500
	CUDA block size         : 128
	Gauss points per element: 4
	Gauss points near singlr: 19
	1D Gauss points per side: 9
	GMRES tolerance         : 1e-05
	GMRES max iterations    : 1000
	GMRES restart iteration : 200

### NanoShaper: 
#### Efield = 5.5264e-5 y _k_ = 0.086

In [1]:
from numpy import *
from pylab import *
import os

#Esolv = array([-701.6664, -617.4536, -585.6496]) #kcal/mol sin campo
Esolv = array([-714.3092, -630.0634, -598.2773, -584.9413]) #kcal/mol con campo EF:5.5264e-5
#N=array([10428, 20200, 43244, 91116])  #N° Elementos
N = array([2, 4, 8, 16])

r= N[3]/N[2]
p = log((Esolv[2] - Esolv[1])/(Esolv[3] - Esolv[2]))/log(r)
print("p_solv: ", p)
fsolvanalitico = Esolv[3] + ((Esolv[3] - Esolv[2])/((r**p) - 1))
print('E_solv_analitico:',fsolvanalitico,'Kcal/mol')

p_solv:  1.25307000623
E_solv_analitico: -575.301845688 Kcal/mol


In [2]:
PyGerr_solv = abs(Esolv-fsolvanalitico)/abs(fsolvanalitico)
print(PyGerr_solv*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="$E_{0} = 5.5264e-05$")
loglog(N, 0.3/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.25e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1,100,0.0001, 1])
legend(loc='lower right', fontsize = '6')
savefig('Error_1hel_Esolv_Ef5.5264e-5_k0.086_nanoshaper.pdf')
clf()

[ 24.16250797   9.51875172   3.99363473   1.67554726]


### MSMS: 
#### Efield = 0 kappa = 0.086

In [3]:
Esolv = array([-634.8094, -578.3930, -565.5083, -560.3698])
#N=array([14178, 21914, 42300, 81144])  #N° Elementos
N = array([2, 4, 8, 16])

r= 2
p = log((Esolv[1] - Esolv[2])/(Esolv[2] - Esolv[3]))/log(r)
print("p_solv: ", p)
fsolvanalitico = Esolv[3] + ((Esolv[3] - Esolv[2])/((r**p) - 1))
print('E_solv_analitico:',fsolvanalitico,'Kcal/mol')

p_solv:  1.32623976357
E_solv_analitico: -556.961137398 Kcal/mol


In [4]:
PyGerr_solv = abs(Esolv-fsolvanalitico)/abs(fsolvanalitico)
print(PyGerr_solv*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="$E_{0} = 0$")
loglog(N, 0.12/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.5e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1,100,0.0001, 1])
legend(loc='lower right', fontsize = '6')
savefig('Error_1hel_Esolv_Ef0_k0.086_msms.pdf')
clf()

[ 13.97732398   3.84799965   1.53460664   0.61201085]


#### Efield = 5.5264e-5 kappa = 0.086

In [5]:
Esolv = array([-647.5146, -591.0499, -578.1605, -573.0363])
#N=array([14178, 21914, 42300, 81144])  #N° Elementos
N = array([2, 4, 8, 16])

r= 2
p = log((Esolv[1] - Esolv[2])/(Esolv[2] - Esolv[3]))/log(r)
print("p_solv: ", p)
fsolvanalitico = Esolv[3] + ((Esolv[3] - Esolv[2])/((r**p) - 1))
print('E_solv_analitico:',fsolvanalitico,'Kcal/mol')

p_solv:  1.33078641701
E_solv_analitico: -569.654877031 Kcal/mol


In [6]:
PyGerr_solv = abs(Esolv-fsolvanalitico)/abs(fsolvanalitico)
print(PyGerr_solv*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="$E_{0} = 0$")
loglog(N, 0.12/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.5e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1,100,0.0001, 1])
legend(loc='lower right', fontsize = '6')
savefig('Error_1hel_Esolv_Ef5.5264e-5_k0.086_msms.pdf')
clf()

[ 13.66787613   3.75578685   1.49311861   0.59359151]


### Lisozima 1hel cerca de Surf. Cargada C= -0.04 C/m2 sometida a un Campo Electrico Externo

#### Parametros PyGBe

	Use GPU                 : 1
	P                       : 4
	threshold               : 0.50
	theta                   : 0.50
	NCRIT                   : 500
	CUDA block size         : 128
	Gauss points per element: 2
	Gauss points near singlr: 19
	1D Gauss points per side: 9
	GMRES tolerance         : 1e-05
	GMRES max iterations    : 1000
	GMRES restart iteration : 200

### NanoShaper
#### Efield = 0.0 y _k_ = 0.086

In [7]:
Esolv = array([-702.7427, - 618.5601, -586.7376, -573.4455]) #kcal/mol sin campo
Esurf = array([15.2229, 15.2362, 15.2557, 15.2612]) #kcal/mol sin campo
#Esolv = array([-722.6692, -638.5672, -606.8794, -593.6063]) #kcal/mol con campo EF:5.5264e-5
#Esurf = array([-18.7799, -18.7691, -18.7500]) #kcal/mol con campo EF:5.5264e-5
NN=array([25128, 49012, 102044, 206034])#N° Elementos
N = array([2, 4, 8, 16])

r= 2
r_surf = 0.5
p_solv = log((Esolv[2] - Esolv[1])/(Esolv[3] - Esolv[2]))/log(r)
p_surf = log((Esurf[1] - Esurf[0])/(Esurf[2] - Esurf[1]))/log(r_surf)
print("p_solv: ", p_solv)
print("p_surf: ", p_surf)
fsolvanalitico = Esolv[3] + ((Esolv[3] - Esolv[2])/((r**p) - 1))
fsurfanalitico = Esurf[2] + ((Esurf[2] - Esurf[1])/((r**p) - 1))
print('E_solv_analitico:',fsolvanalitico,'Kcal/mol')
print('E_surf_analitico:',fsurfanalitico,'Kcal/mol')

p_solv:  1.25947812739
p_surf:  0.552047878248
E_solv_analitico: -564.674138178 Kcal/mol
E_surf_analitico: 15.2685679107 Kcal/mol


In [8]:
PyGerr_solv = abs(Esolv-fsolvanalitico)/abs(fsolvanalitico)
print(PyGerr_solv*100)
PyGerr_surf = abs(Esurf-fsurfanalitico)/abs(fsurfanalitico)
print(PyGerr_surf*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="$E_{solv}$")
loglog(N, 0.35/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
loglog(N, PyGerr_surf, c='k', marker='^', mfc='w', ms=3, ls='', lw=0.5, label="$E_{surf}$")
loglog(N, 0.009/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.25e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1,100,0.0001, 1])
legend(loc='lower right', fontsize = '6')
#savefig('Error_1hel-sensor_Esolv_Ef5.5264e-5_k0.086.pdf')
savefig('Error_1hel-sensor_Esolv_Ef0.0_k0.086_nanoshaper.pdf')
clf()

[ 24.45101564   9.54284218   3.90729101   1.55334931]
[ 0.29909754  0.21199048  0.08427713  0.04825541]


#### Efield = 5.5264e-5 y _k_ = 0.086

In [73]:
Esolv = array([-722.6692, -638.5672, -606.8794, -593.6063]) #kcal/mol con campo EF:5.5264e-5
Esurf = array([-18.7799, -18.7691, -18.7498, -18.7513]) #kcal/mol con campo EF:5.5264e-5
NN=array([25128, 49012, 102044, 206034])#N° Elementos
N = array([2, 4, 8, 16])

r= 2.0
r_surf = 2.0
p_solv = log((Esolv[2] - Esolv[1])/(Esolv[3] - Esolv[2]))/log(r)
p_surf = log((Esurf[1] - Esurf[0])/(Esurf[2] - Esurf[1]))/log(r_surf)
print("p_solv: ", p_solv)
print("p_surf: ", p_surf)
fsolvanalitico = Esolv[3] + ((Esolv[3] - Esolv[2])/((r**p) - 1))
fsurfanalitico = Esurf[2] + ((Esurf[2] - Esurf[1])/((r**p) - 1))
print('E_solv_analitico:',fsolvanalitico,'Kcal/mol')
print('E_surf_analitico:',fsurfanalitico,'Kcal/mol')

asymp_solv = NN[-1]*Esolv_error[-1]/NN
asymp_surf = NN[-2]*Esurf_error[-2]/NN


p_solv:  1.25542214188
p_surf:  -0.837569535105
E_solv_analitico: -584.847476142 Kcal/mol
E_surf_analitico: -18.7370640679 Kcal/mol


In [74]:
PyGerr_solv = abs(Esolv-fsolvanalitico)/abs(fsolvanalitico)
print(PyGerr_solv*100)
PyGerr_surf = abs(Esurf-fsurfanalitico)/abs(fsurfanalitico)
print(PyGerr_surf*100)
figure(figsize=(3,2), dpi=80)
loglog(NN, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="$E_{solv}$")
loglog(NN, asymp_solv, c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
loglog(NN, PyGerr_surf, c='k', marker='^', mfc='w', ms=3, ls='', lw=0.5, label="$E_{surf}$")
loglog(NN, asymp_surf, c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
ylabel('error relativo', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.92, top=0.92)
axis([10000,1000000,0.000001, 1])
legend(loc='lower right', fontsize = '6')
#savefig('Error_1hel-sensor_Esolv_Ef5.5264e-5_k0.086.pdf')
savefig('Error_1hel-sensor_Esolv_Ef5.5264e-5_k0.086_nanoshaper.pdf')
clf()

[ 23.56541312   9.1852536    3.76712301   1.49762532]
[ 0.22861603  0.17097626  0.06797187  0.07597739]


#### Otra forma de extrapolacion

In [50]:
#Esolv = array([-722.6692, -638.5672, -606.8794, -593.6063]) #kcal/mol con campo EF:5.5264e-5
#Esurf = array([-18.7799, -18.7691, -18.7498, -18.7513]) #kcal/mol con campo EF:5.5264e-5
#Esurf = array([-16.87029,-16.87102,-16.87139, -16.87156]) #con campo sensor aislado
#Esolv = array([-1037.3965, -722.6692, -638.5672, -606.8794]) #kcal/mol con campo EF:5.5264e-5
#Esurf = array([-18.7192, -18.7799, -18.7691, -18.7498]) #kcal/mol con campo EF:5.5264e-5
#NN=array([25128, 49012, 102044, 206034])#N° Elementos
#NN=array([12864, 25128, 49012, 102044])#N° Elementos
#Esolv_extra = (Esolv[-3]*Esolv[-1]-Esolv[-2]*Esolv[-2])/(Esolv[-1]-2*Esolv[-2]+Esolv[-3])
#Esurf_extra = (Esurf[-1]*Esurf[-3]-Esurf[-2]*Esurf[-2])/(Esurf[-1]-2*Esurf[-2]+Esurf[-3])
#Esolv_error = abs(Esolv-Esolv_extra)/abs(Esolv_extra)
#Esurf_error = abs(Esurf-fsurfanalitico)/abs(fsurfanalitico)
#asymp_solv = NN[-2]*Esolv_error[-2]/NN
#asymp_surf = NN[-2]*Esurf_error[-2]/NN

In [51]:
#print(Esolv_extra)
#print(Esurf_extra)
#print(Esolv_error)
#print(Esurf_error)
#print(asymp_solv)
#print(asymp_surf)

In [52]:
#figure(figsize=(3,2), dpi=80)
#loglog(NN, Esolv_error, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="$E_{solv}$")
#loglog(NN, asymp_solv, c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
#loglog(NN, Esurf_error, c='k', marker='^', mfc='w', ms=3, ls='', lw=0.5, label="$E_{surf}$")
#loglog(NN, asymp_surf, c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
#text(3e3, 0.25e-3,'1/N',fontsize=4,rotation=-8)
#ylabel('error relativo', fontsize=10)
#xlabel('N mesh',fontsize=10)
#subplots_adjust(left=0.25, bottom=0.25, right=0.92, top=0.92)
#axis([10000,1000000,0.000001, 1])
#legend(loc='lower right', fontsize = '6')
#savefig('Error_1hel-sensor_Esolv_Ef5.5264e-5_k0.086.pdf')
#savefig('Error_test.pdf')
#clf()