## Estudio de Convergencia: Calculos con Bempp

### Esfera con Carga Electrica Puntual sometido a un Campo Electrico Externo

#### Efield = 2.4

In [1]:
from numpy import *
from pylab import *
import os


os.system('mkdir Convergencia/')
#Esolv = array([-13.2819,-13.2640,-13.2549])
Esolv = array([-14316.3840,-14318.4438,-14319.3562])
N=array([2348,4744,9414])

#fsolvanalitico=-13.056635
fsolvanalitico=-14320.109206
print('E_solv_extrapolado:',fsolvanalitico,'Kcal/mol')

E_solv_extrapolado: -14320.109206 Kcal/mol


In [2]:
PyGerr = abs(Esolv-fsolvanalitico)/abs(fsolvanalitico)
figure(figsize=(3,2), dpi=80)
print(PyGerr)
loglog(N, PyGerr, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="E = 2.4")
loglog(N, 1./(N*2), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.25e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1000,20000,0.0000001, 1])
legend(loc='lower right')
savefig('Convergencia/Error_Esfera_Ef2.4_bempp.pdf')
clf()

[2.60138100e-04 1.16298415e-04 5.25838169e-05]


<Figure size 240x160 with 0 Axes>

#### Efield = 0.8

In [3]:
Esolv = array([-4780.9856,-4781.6555,-4781.9537])
N=array([2348,4744,9414])

fsolvanalitico=-4782.1999
print('E_solv_extrapolado:',fsolvanalitico,'Kcal/mol')

E_solv_extrapolado: -4782.1999 Kcal/mol


In [4]:
PyGerr = abs(Esolv-fsolvanalitico)/abs(fsolvanalitico)
figure(figsize=(3,2), dpi=80)
print(PyGerr)
print(1./N*5)
loglog(N, PyGerr, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.2, label="E = 0.8")
loglog(N, 1./(N*2), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.25e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1000,20000,0.0000001, 1])
legend(loc='lower right')
savefig('Convergencia/Error_Esfera_Ef0.8_bempp.pdf')
clf()

[2.53920795e-04 1.13838821e-04 5.14825823e-05]
[0.00212947 0.00105396 0.00053112]


<Figure size 240x160 with 0 Axes>

#### Efield = 0

In [5]:
Esolv = array([-13.2819,-13.2640,-13.2549])
N=array([2348,4744,9414])

fsolvanalitico=-13.245345
print('E_solv_extrapolado:',fsolvanalitico,'Kcal/mol')

E_solv_extrapolado: -13.245345 Kcal/mol


In [6]:
PyGerr = abs(Esolv-fsolvanalitico)/abs(fsolvanalitico)
figure(figsize=(3,2), dpi=80)
print(PyGerr)
print(1./N*5)
loglog(N, PyGerr, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.8,label="E = 0")
loglog(N, 6.5/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3.1e3, 3e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1000,20000,0.0000001, 1])
legend(loc='lower right')
savefig('Convergencia/Error_Esfera_Ef0.0_bempp.pdf')
clf()

[0.00275984 0.00140842 0.00072139]
[0.00212947 0.00105396 0.00053112]


<Figure size 240x160 with 0 Axes>