## Estudio de Convergencia: Calculos con PyGBe

### Esfera con Carga Electrica Puntual sometido a un Campo Electrico Externo

#### Parametros PyGBe

	Use GPU                 : 0
	P                       : 15
	threshold               : 0.50
	theta                   : 0.50
	NCRIT                   : 500
	CUDA block size         : 128
	Gauss points per element: 3
	Gauss points near singlr: 19
	1D Gauss points per side: 9
	GMRES tolerance         : 1e-05
	GMRES max iterations    : 1000
	GMRES restart iteration : 200

#### Efield = 0. y _k_ = 0.125

In [1]:
from numpy import *
from pylab import *
import os


os.system('mkdir convergencia_kappa0.125/')

Esolv = array([-13.287369, -13.266583, -13.256178]) #kcal/mol
N=array([2348, 4744, 9414])  #N° Elementos

fsolvanalitico_solv= -13.245345  #kcal/mol

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
print("p_solv: ", p_solv)
#fsolvanalitico = Esolv[2] + ((Esolv[2] - Esolv[1])/((r**p) - 1))
print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')

p_solv:  0.998335191613
E_solv_analitico: -13.245345 Kcal/mol


In [2]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.2, label="$E_{0} = 0.0$")
loglog(N, 8./(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.35e-2,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.92)
axis([1000,50000,0.000001, 1])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_kappa0.125/Error_Esfera_Esolv_Ef0.0_k0.125_pygbe.pdf')
clf()

#### Efield = 0.8 y _k_ = 0.125

In [10]:
Esolv = array([-4782.702861, -4782.473759, -4782.346926]) #kcal/mol docker
N=array([2348, 4744, 9414])  #N° Elementos

fsolvanalitico_solv= -4782.199966  #kcal/mol

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
print("p_solv: ", p_solv)
#fsolvanalitico = Esolv[2] + ((Esolv[2] - Esolv[1])/((r**p) - 1))
print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')

p_solv:  0.853059891612
E_solv_analitico: -4782.199966 Kcal/mol


In [16]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
print(PyGerr_solv*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="$E_{0} = 0.8$")
loglog(N, 0.25/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.15e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=7)
xlabel('N mesh',fontsize=7)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.92)
axis([1000,50000,0.000000001, 1])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_kappa0.125/Error_Esfera_Esolv_Ef0.8_k0.125_pygbe.pdf')
clf()

[ 0.01051598  0.00572525  0.00307306]


#### Efield = 1.6 y _k_ = 0.125

In [5]:
Esolv = array([-9552.118334, -9551.681132, -9551.437764]) #kcal/mol
N=array([2348, 4744, 9414])  #N° Elementos

fsolvanalitico_solv= -9551.154586  #kcal/mol

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
print("p_solv: ", p_solv)
#fsolvanalitico = Esolv[2] + ((Esolv[2] - Esolv[1])/((r**p) - 1))
print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')

p_solv:  0.845160517436
E_solv_analitico: -9551.154586 Kcal/mol


In [6]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
print(PyGerr_solv)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="$E_{0} = 1.6$")
loglog(N, 0.25/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.15e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1000,50000,0.000000001, 1])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_kappa0.125/Error_Esfera_Esolv_Ef1.6_k0.125_pygbe.pdf')
clf()

[  1.00903822e-04   5.51290418e-05   2.96485621e-05]


#### Efield = 2.4 y _k_ = 0.125

In [7]:
Esolv = array([-14321.533806, -14320.888511,  -14320.528602]) #kcal/mol
N=array([2348, 4744, 9414])  #N° Elementos

fsolvanalitico_solv= -14320.109206  #kcal/mol

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
print("p_solv: ", p_solv)
#fsolvanalitico = Esolv[2] + ((Esolv[2] - Esolv[1])/((r**p) - 1))
print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')

p_solv:  0.842326667752
E_solv_analitico: -14320.109206 Kcal/mol


In [8]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
print(PyGerr_solv)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="$E_{0} = 2.4$")
loglog(N, 0.25/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.15e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1000,50000,0.000000001, 1])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_kappa0.125/Error_Esfera_Esolv_Ef2.4_k0.125_pygbe.pdf')
clf()

[  9.94824816e-05   5.44203252e-05   2.92872068e-05]


#### Efield = 0. y _k_ = 1e-12

In [9]:
from numpy import *
from pylab import *
import os


os.system('mkdir convergencia_kappa1e-12/')

Esolv = array([-13.098453, -13.077774, -13.067419]) #kcal/mol
N=array([2348, 4744, 9414])  #N° Elementos

fsolvanalitico_solv= -13.056635  #kcal/mol

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
print("p_solv: ", p_solv)
print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')

p_solv:  0.997838867591
E_solv_analitico: -13.056635 Kcal/mol


In [10]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="E = 0.0")
loglog(N, 8./(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.25e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1000,100000,0.0000001, 1])
legend(loc='lower right')
savefig('convergencia_kappa1e-12/Error_Esfera_Esolv_Ef0.0_k0.0_pygbe.pdf')
clf()

#### Efield = 0.8 y _k_ = 1e-12

In [11]:
Esolv = array([-4898.617036, -4898.494954, -4898.420426]) #kcal/mol
N=array([2348, 4744, 9414])  #N° Elementos

fsolvanalitico_solv= -4898.32722  #kcal/mol

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
print("p_solv: ", p_solv)
print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')

p_solv:  0.711996052554
E_solv_analitico: -4898.32722 Kcal/mol


In [12]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="E = 0.8")
loglog(N, 0.15/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.25e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1000,100000,0.0000001, 1])
legend(loc='lower right')
savefig('convergencia_kappa1e-12/Error_Esfera_Esolv_Ef0.8_k0.0_pygbe.pdf')
clf()

#### Efield = 1.6 y _k_ = 1e-12

In [13]:
Esolv = array([-9784.135606, -9783.912335, -9783.773522]) #kcal/mol
N=array([2348, 4744, 9414])  #N° Elementos

fsolvanalitico_solv= -9783.597808  #kcal/mol

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
print("p_solv: ", p_solv)
print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')

p_solv:  0.685653191656
E_solv_analitico: -9783.597808 Kcal/mol


In [14]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="E = 1.6")
loglog(N, 0.15/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.25e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1000,100000,0.0000001, 1])
legend(loc='lower right')
savefig('convergencia_kappa1e-12/Error_Esfera_Esolv_Ef1.6_k0.0_pygbe.pdf')
clf()

#### Efield = 2.4 y _k_ = 1e-12

In [15]:
Esolv = array([-14669.654176, -14669.329722, -14669.126618]) #kcal/mol
N=array([2348, 4744, 9414])  #N° Elementos

fsolvanalitico_solv= -14668.868395  #kcal/mol

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
print("p_solv: ", p_solv)
print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')

p_solv:  0.675795299409
E_solv_analitico: -14668.868395 Kcal/mol


In [16]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.5, label="E = 2.4")
loglog(N, 0.15/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(3e3, 0.25e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.96)
axis([1000,100000,0.0000001, 1])
legend(loc='lower right')
savefig('convergencia_kappa1e-12/Error_Esfera_Esolv_Ef2.4_k0.0_pygbe.pdf')
clf()