In [2]:
from numpy import *
from pylab import *

### Esfera con Carga Electrica Puntual cerca de Superficie Esferica con Densidad de Carga bajo a un Campo Electrico Externo

#### Parametros PyGBe

	Use GPU                 : 0
	P                       : 15
	threshold               : 0.50
	theta                   : 0.50
	NCRIT                   : 500
	CUDA block size         : 128
	Gauss points per element: 3
	Gauss points near singlr: 19
	1D Gauss points per side: 9
	GMRES tolerance         : 1e-05
	GMRES max iterations    : 1000
	GMRES restart iteration : 200

#### Efield = 0. y _k_ = 0.125

In [3]:
Esolv = array([-847.193807643251,-848.4670797997973, -849.0789496892962 ]) #kcal/mol
Esurf = array([89425043.0246972, 89556308.46127957, 89619564.86597002]) #kcal/mol
N=array([2348*2, 4744*2, 9414*2])  #N° Elementos
E0 = 0.0
fsolvanalitico_solv = -849.695872875 
fsolvanalitico_surf = 89683115.3048 

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
p_surf = log((Esurf[0] - Esurf[1])/(Esurf[1] - Esurf[2]))/log(r)
print("p_solv: ", p_solv)
print("p_surf: ", p_surf)

print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')
print('E_surf_analitico:',fsolvanalitico_surf,'Kcal/mol')

p_solv:  1.05724401207
p_surf:  1.05320362641
E_solv_analitico: -849.695872875 Kcal/mol
E_surf_analitico: 89683115.3048 Kcal/mol


In [4]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
print(PyGerr_solv*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.2, label="$E_{solv}$: $E_{0} = 0.0$ - $\sigma_{0} = -80$")
loglog(N, 12./(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(6e3, 0.35e-2,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.92)
axis([1000,50000,0.000001, 1])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_surf_charged_kappa0.125/Error_Esferas_Esolv_Ef0.0_k0.125_pygbe.pdf')
clf()

[ 0.29446597  0.14461563  0.07260518]


In [5]:
PyGerr_surf = abs(Esurf-fsolvanalitico_surf)/abs(fsolvanalitico_surf)
print(PyGerr_surf*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_surf, c='k', marker='1', mfc='w', ms=3, ls='', lw=0.2, label="$E_{surf}$: $E_{0} = 0.0$ - $\sigma_{0} = -80$")
loglog(N, 12./(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(6e3, 0.35e-2,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esurf', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.92)
axis([1000,50000,0.000001, 1])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_surf_charged_kappa0.125/Error_Esferas_Esurf_Ef0.0_k0.125_pygbe.pdf')
clf()

[ 0.28776016  0.14139433  0.0708611 ]


#### Efield = 0.8 y _k_ = 0.125

In [6]:
Esolv = array([-5363.550562034498,-5364.084485854837,-5364.305248958319]) #kcal/mol
Esurf = array([466338009.86767906,467004510.1886354,467330796.6174517]) #kcal/mol
N=array([2348*2, 4744*2, 9414*2])  #N° Elementos
E0 = 0.8
fsolvanalitico_solv = -5364.45659214  
fsolvanalitico_surf = 467661874.588  

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
p_surf = log((Esurf[0] - Esurf[1])/(Esurf[1] - Esurf[2]))/log(r)
print("p_solv: ", p_solv)
print("p_surf: ", p_surf)

print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')
print('E_surf_analitico:',fsolvanalitico_surf,'Kcal/mol')

p_solv:  1.27413484231
p_surf:  1.03046658718
E_solv_analitico: -5364.45659214 Kcal/mol
E_surf_analitico: 467661874.588 Kcal/mol


In [7]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
print(PyGerr_solv*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.2, label="$E_{solv}$: $E_{0} = 0.8$ - $\sigma_{0} = -80$")
loglog(N, 0.6/(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(6e3, 0.2e-3,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.92)
axis([1000,50000,0.000000001, 0.01])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_surf_charged_kappa0.125/Error_Esferas_Esolv_Ef0.8_k0.125_pygbe.pdf')
clf()

[ 0.0168895   0.00693651  0.00282122]


In [8]:
PyGerr_surf = abs(Esurf-fsolvanalitico_surf)/abs(fsolvanalitico_surf)
print(PyGerr_surf*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_surf, c='k', marker='1', mfc='w', ms=3, ls='', lw=0.2, label="$E_{surf}$: $E_{0} = 0.8$ - $\sigma_{0} = -80$")
loglog(N, 12./(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(6e3, 0.35e-2,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esurf', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.92)
axis([1000,50000,0.000001, 1])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_surf_charged_kappa0.125/Error_Esferas_Esurf_Ef0.8_k0.125_pygbe.pdf')
clf()

[ 0.2830816   0.14056403  0.0707943 ]


#### Efield = -0.8 y _k_ = 0.125

In [9]:
Esolv = array([3669.1938070475626,3667.153054123416,3666.131801712373]) #kcal/mol
Esurf = array([-287487974.2853614,-287892072.1235804,-288091734.08589244]) #kcal/mol
N=array([2348*2, 4744*2, 9414*2])  #N° Elementos
E0 = -0.8
fsolvanalitico_solv = 3665.06484639  
fsolvanalitico_surf = -288295643.979

r=2
p_solv = log((Esolv[0] - Esolv[1])/(Esolv[1] - Esolv[2]))/log(r)
p_surf = log((Esurf[0] - Esurf[1])/(Esurf[1] - Esurf[2]))/log(r)
print("p_solv: ", p_solv)
print("p_surf: ", p_surf)

print('E_solv_analitico:',fsolvanalitico_solv,'Kcal/mol')
print('E_surf_analitico:',fsolvanalitico_surf,'Kcal/mol')

p_solv:  0.998762040125
p_surf:  1.01714512314
E_solv_analitico: 3665.06484639 Kcal/mol
E_surf_analitico: -288295643.979 Kcal/mol


In [10]:
PyGerr_solv = abs(Esolv-fsolvanalitico_solv)/abs(fsolvanalitico_solv)
print(PyGerr_solv*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_solv, c='k', marker='o', mfc='w', ms=3, ls='', lw=0.2, label="$E_{solv}$: $E_{0} = -0.8$ - $\sigma_{0} = -80$")
loglog(N, 5./(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(6e3, 0.1e-2,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esolv', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.92)
axis([1000,50000,0.000001, 1])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_surf_charged_kappa0.125/Error_Esferas_Esolv_Ef-0.8_k0.125_pygbe.pdf')
clf()

[ 0.11265723  0.05697601  0.0291115 ]


In [11]:
PyGerr_surf = abs(Esurf-fsolvanalitico_surf)/abs(fsolvanalitico_surf)
print(PyGerr_surf*100)
figure(figsize=(3,2), dpi=80)
loglog(N, PyGerr_surf, c='k', marker='1', mfc='w', ms=3, ls='', lw=0.2, label="$E_{surf}$: $E_{0} = -0.8$ - $\sigma_{0} = -80$")
loglog(N, 12./(N), c='k', marker='', mfc='w', ms=3, ls=':', lw=0.8, label=None)
text(6e3, 0.35e-2,'1/N',fontsize=4,rotation=-8)
ylabel('Error Esurf', fontsize=10)
xlabel('N mesh',fontsize=10)
subplots_adjust(left=0.25, bottom=0.25, right=0.96, top=0.92)
axis([1000,50000,0.000001, 1])
legend(loc='lower right', fontsize = 7)
savefig('convergencia_surf_charged_kappa0.125/Error_Esferas_Esurf_Ef-0.8_k0.125_pygbe.pdf')
clf()

[ 0.28015328  0.13998542  0.07072944]
